CPU 8086
ORG 0X0100
	MOV AL, 0XAA		;TEST CONTROLLER
	OUT 0X64, AL		;OUT COMMAND PORT

	MOV CX, 0XFFFF		;DELAY 
	DB 0XE2, 0XFE		;LOOP BACK
	MOV CX, 0XFFFF		;DELAY 
	DB 0XE2, 0XFE		;LOOP BACK
	IN AL, 0X60		;READ DATA PORT

	MOV AL, 0X60		;WRITE COMMAND BYTE
	OUT 0X64, AL		;OUT COMMAND PORT
	MOV AL, 0X41		;COMMAND BYTE
	OUT 0X60, AL		;OUT DATA PORT 
	
	MOV AL, 0XB6		;SPEAKER COMMAND 
	OUT 0X43, AL		;OUT TO CONTROL REGISTER

	RET			;RET